baseurl = "https://tristor.ro/"
languageCode = "en-us"
theme = "blackburn"
title = "Wandering in Wondering"
description = "Tyler Duzan's personal website covering topics related to technology, DevOps, Product Management, cooking, cars, travel, photography, and other interests."
author = "Tyler Duzan"
copyright = "&copy; 2021 <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Licensed CC:By-NC-SA</a>"
canonifyurls = true

# Allow raw HTML rendering mixed with Markdown
[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[pagination]
pagerSize = 10

[permalinks]
  post = "/blog/:year/:month/:day/:slug/"
  page = "/:filename/"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Code, Coffee, Photography, and Travel"
  brand = "Wandering<br>in<br>Wondering"
  # Disaling Google Analytics
  #googleAnalytics = "UA-74523510-1"
  goatcounterAnalytics = "tristor"
  # Disabling Disqus
  #disqus = "wanderinginwondering"
  commento = "tristor.ro"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04 MST"
  # Custom CSS
  custom_css = ["css/resume.css"]
  # Must provide a fully qualified path
  pgpkey = "https://tristor.ro/files/tyler.duzan.asc"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 1
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Resume"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "resume"
    url = "/resume/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Gallery"
    pre = "<i class='fa fa-camera fa-fw'></i>"
    weight = 4
    identifier = "gallery"
    url = "/gallery/"
  [[menu.main]]
    name = "Cars"
    pre = "<i class='fa fa-car fa-fw'></i>"
    weight = 5
    identifier = "cars"
    url = "/cars/"
  [[menu.main]]
    name = "Cooking"
    pre = "<i class='fa fa-utensils fa-fw'></i>"
    weight = 6
    identifier = "cooking"
    url = "/cooking/"
  [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 7
    identifier = "topic"
    url = "/topics/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 8
    identifier = "tag"
    url = "/tags/"

[params.social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  flickr = "totaledcow"
  twitter = "tristor"
  github = "tristor"
  linkedin = "tylerduzan"
  hackernews = "tristor"
  instagram = "tristor86"
  keybase = "tristor"
